### ISSUE TITLE
Example should be renamed to include simpletest

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_OneWire#12]
Example `onewire_demo.py` should be renamed to `onewire_simpletest.py` to fit with CircuitPython library standards.

The lines including this file name in the `docs/examples.rst` file must also be updated to reflect the name change, e.g.:
```
.. literalinclude:: ../examples/current_file_name.py
    :caption: examples/current_file_name.py
    :linenos:
```
would be updated to:
```
.. literalinclude:: ../examples/current_file_name_changed.py
    :caption: examples/current_file_name_changed.py
    :linenos:
```

**Comment by sreekaransrinath** [comment]
Hey, I'd like to take this issue up!

**Comment by ladyada** [comment]
go for it!!! 🎃

**Comment by sreekaransrinath** [comment]
Yeah, I finished it right after I commented :)

**Comment by shlok-goud** [comment]
Hi. I would like to take up this issue for my first pull requests.

**Comment by ladyada** [comment]
@shlok-goud oops this was already done
https://github.com/adafruit/Adafruit_CircuitPython_OneWire/pull/13
we have lots more hacktober PRs very similar to this one!
