### ISSUE TITLE
OneWire has not been implemented

### ISSUE THREAD

**Issue by bartvstratum** [adafruit/Adafruit_CircuitPython_OneWire#21]
There was already a similar issue posted [here](https://github.com/adafruit/Adafruit_CircuitPython_OneWire/issues/11), but unfortunately the "solution" was a bit vague (in my opinion...).

Following [the documentation on PyPi](https://pypi.org/project/adafruit-circuitpython-onewire/) I installed OneWire with:

    pip3 install adafruit-circuitpython-onewire

On a Raspberry Pi Zero. Running the example code from that page:

    import board
    from adafruit_onewire.bus import OneWireBus
    ow_bus = OneWireBus(board.D2)
    devices = ow_bus.scan()
    for d in devices:
        print("ROM={}\tFamily=0x{:02x}".format(d.rom, d.family_code))

results in:

    pi@meteo-pi-bvs:~/meteo/pimeteo $ python3 test.py 
    Traceback (most recent call last):
      File "test.py", line 15, in <module>
        ow_bus = OneWireBus(board.D2)
      File "/home/pi/.local/lib/python3.7/site-packages/adafruit_onewire/bus.py", line 79, in __init__
        self._ow = busio.OneWire(pin)
      File "/home/pi/.local/lib/python3.7/site-packages/busio.py", line 431, in __init__
        raise NotImplementedError("OneWire has not been implemented")
    NotImplementedError: OneWire has not been implemented

I really don't understand the _"yah! we dont support onewire thru blinka - you can use the sysfs 1-wire library system instead (we have no way to access 1-wire data outside the kernel)"_ posted in the previous issue. According to the documentation, this should work on a Raspberry Pi. Then why doesn't it work?

**Comment by ladyada** [comment]
there is no low level interface for 1 wire on linux/raspberry pi like there is for uart/i2c/spi/i2s..., so you must use the kernel level 1-wire interfaces.

@dherrada wanna update that readme to remove the raspberry pi details?

**Comment by evaherrada** [comment]
@ladyada Sure

**Comment by evaherrada** [comment]
@ladyada Ok, just removed the 'Installing from PyPI' section

**Comment by ladyada** [comment]
alight hopefully that will help. perhaps one day there will be a kernel module that lets us 1wire in userspace :)

**Comment by Arthur-66** [comment]
The current Circuitpython guide for DS18B20 still indiretly suggests the DS18B20 and Onewire can be used on the Raspberry Pi:
- The OneWire page here https://github.com/adafruit/Adafruit_CircuitPython_DS18X20 which says " ...On supported GNU/Linux systems like the Raspberry Pi, ..." and indirectly on:
- https://github.com/adafruit/Adafruit_CircuitPython_OneWire which does not state that it does not make sense to install onewire on the RPi to support the DS18B20.
I spent quite a bit of time trying to figure out what was wrong, before coming accross this thread (doesn't show up in the early pages in DuckDuckGo). Maybe it is a good idea to just put clear warnings on each of the pages that this guide and these drivers cannot be used on the PRi?

**Comment by ladyada** [comment]
@dherrada please update! ^

**Comment by evaherrada** [comment]
@ladyada On it!

**Comment by evaherrada** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_DS18X20/pull/21

**Comment by Bluscream** [comment]
Oh no
WHy doesn't the library implement reading the files then :c

**Comment by ladyada** [comment]
because its not a low enough interface. the kernel simply does not expose 'onewire' it only exposes 'complete ds18b20 driver'
