### ISSUE TITLE
MemoryError on scan() when nothing is attached to bus

### ISSUE THREAD

**Issue by NonsenseInc** [adafruit/Adafruit_CircuitPython_OneWire#7]
When no sensor is attached to the OneWire bus on calling scan() a MemoryError occurs:

```python
Adafruit CircuitPython 2.3.1 on 2018-05-07; Adafruit CircuitPlayground Express with samd21g18
>>> import board
>>> from adafruit_onewire.bus import OneWireBus
>>> ow_bus = OneWireBus(board.D5)
>>> ow_bus.scan()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_onewire/bus.py", line 133, in scan
MemoryError: memory allocation failed, allocating 1024 bytes
```

I tested this on a Trinket M0, Feather M0 express and Feather M0 basic with CircuitPython 2.2.0, 2.3.1 and the 3.0 beta.

I tested the negative (with sensor attached and working) on Trinket M0 and Feather M0 basic with CircuitPython 2.3.1.

**Comment by caternuson** [comment]
The scan currently has no limit check. It would be pretty easy to add one, but not sure what the max value should be. Maybe just set it to something sane, `10`? And if someone actually has more devices they can bump it up.

Probably related:
https://github.com/adafruit/Adafruit_CircuitPython_DS18X20/issues/7

**Comment by ladyada** [comment]
max 10 is plenty!

**Comment by caternuson** [comment]
Just add a property?
```python
import board
from adafruit_onewire.bus import OneWireBus
ow_bus = OneWireBus(board.D5)
# scan for up to max number of devices, throw error if more are discovered
ow_bus.scan()
# if more actually exist, reset the limit
ow_bus.maximum_devices = 20
```

**Comment by ladyada** [comment]
yep thats fine

**Comment by caternuson** [comment]
PR'd it up: #9

**Comment by caternuson** [comment]
For now, fixed with #9.

**Comment by tannewt** [comment]
@caternuson Why was the solution to add a limit when there is nothing on the bus? Shouldn't we return an empty list in that case?

**Comment by caternuson** [comment]
@tannewt Can't remember exactly, but I think maybe it was because the scan can't distinguish between connected devices and not connected devices, so with nothing connected, it runs open ended.

**Comment by alexwhittemore** [comment]
> @caternuson Why was the solution to add a limit when there is nothing on the bus? Shouldn't we return an empty list in that case?

For my own notes since I know I'll be back here eventually: No attached devices, data pull-up resistor present => empty list returned. No attached devices, data pin floating => hits the max limit. So I think it's to do with the bus idle state being incorrect.
